### PR TITLE
Multiplatform CI

### PR DESCRIPTION
**Pull request by edmundnoble**
cc @Bodigrim

### CODE REVIEW

**Comment by edmundnoble** [comment]
Didn't see this before, but... the tests aren't running on GHC 9.0.1 because bytestring-handle does not "work" with base >=4.15.

**Comment by edmundnoble** [comment]
Alright this looks okay now. Testing 8.10.4 on all platforms, building 9.0.1 on all platforms, testing earlier GHC versions back to 7.10.3 on Ubuntu only.

**Comment by Bodigrim** [comment]
@edmundnoble GitHub happily supports multiple workflows. Let's leave the existing workflow in peace, it is useful to test ancient GHCs and it is autogenerated. I suggest creating an additional workflow running GHC 8.10 with 
```yaml
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, windows-2019, macos-10.15, macos-11.0]
```

Plus one additional workflow for FreeBSD, similar to https://github.com/haskell/bytestring/blob/ba3046d9f5bf5cac1246c39f519b8be7ac11f49c/.github/workflows/ci.yml#L57-L75

Separate workflows are easier to manage, because GitHub allows to rerun a workflow, but not an individual job.

**Comment by Bodigrim** [comment]
Superseded by 3d421d2.

**Pull request closed without merging**
