### PR TITLE
Support bytestring-0.9 via bytestring-builder

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by edsko** [comment]
@dcoutts , if we do go down this route, can we also change the type of `Codec.Archive.Tar.Index.serialise` so that we don't leak the need for `Builder`?

**Comment by phadej** [comment]
@hvr according to travis: no. (and I did guard the imports)

**Comment by hvr** [comment]
@phadej that's only because Travis doesn't pick a situation where `blaze-builder` is used together with GHC 7.10 by default... ;-)  (anyway, looking at `bytestring`'s matrix we can ignore that warning)

**Comment by phadej** [comment]
Ok, no travis is happy.

@hvr commented on some previous commit that should there be bounds on `bytestring-builder`, but I guess its versions are quite restricted by `bytestring`. OTOH I have no strong opinion on that.

**Comment by dcoutts** [comment]
Thanks, will do this.

**Pull request merged**
