### PR TITLE
Decouple library from tests

### PR DESCRIPTION
**Pull request by Bodigrim**
Current setup of tests intermingled with implementation internals, being hidden under a flag, is a headache to deal with. It means that a) source files are recompiled twice, b) IDEs have tough times guessing which module belongs to which build component, c) coverage reports are unusable. 

The simplest way to disentangle this is to create an internal library, and reexport its modules into a public one. This is what is done in this PR. The main obstacle is that reexported modules are unsupported by GHC < 7.10. I can probably work around it with more boilerplate, but how do we actually feel about dropping support of ancient GHCs? CC @emilypi @hasufell

### CODE REVIEW

**Comment by emilypi** [comment]
I'm in favor of dropping GHC's up to the point where it's reasonable to locally test, which means 8.0 or 8.2

**Comment by hasufell** [comment]
This will likely cause a lot of merge conflicts with existing PRs. I advise against merging this for now, especially since it doesn't fix any urgent bugs.

Wrt the change itself: yes, it makes sense.

**Comment by Bodigrim** [comment]
> I'm in favor of dropping GHC's up to the point where it's reasonable to locally test, which means 8.0 or 8.2

@fgaz @gbaz would it be all right from Cabal and Hackage perspective?

**Comment by gbaz** [comment]
For hackage, certainly!

**Comment by fgaz** [comment]
I think so. There were plans to do the same for cabal anyway, right @emilypi?

**Comment by Bodigrim** [comment]
> This will likely cause a lot of merge conflicts with existing PRs. I advise against merging this for now, especially since it doesn't fix any urgent bugs.

@hasufell I've undone moving source files into `src/`, so it is less disruptive now. Do you foresee any specific difficulties now?

**Comment by hasufell** [comment]
> Do you foresee any specific difficulties now?

It still changes language pragmas and import lines. That's a frequent source of merge conflicts. E.g. I just had to rebase against master due to https://github.com/haskell/tar/commit/1f16e92e4c6673b0d0b07689434a539248ecfec1#diff-ccf4f59eaf70146f650611410832bd00fba27e3fe303d14cf6a24c7710726dba and it took about half an hour, because I didn't want to squash my commits. So you have to fix conflicts for every single commit in your PR.

I'd prioritize bugfix PRs over maintenance PRs.

**Comment by emilypi** [comment]
> I think so. There were plans to do the same for cabal anyway, right @emilypi?

@fgaz This is a larger discussion, but yes. In the next few PRs, I'd like to move the baseline to at least 8.0 on `cabal-install`. Perhaps not `Cabal`, but certainly the  executable.

**Comment by hasufell** [comment]
@Bodigrim on second thought... maybe just merge this after #26, because I intended to create roundtrip tests for #50 and it will probably be easier to start based on this patchset.

**Review by emilypi — APPROVED** [review]

**Comment by hasufell** [comment]
> Do you foresee any specific difficulties now?

Yeah. `Codec.Archive.Tar.Index` was more or less deleted and moved into an internal module. Can we revert that?

**Comment by Bodigrim** [comment]
@hasufell if it could help, I rebased your branch from #50 atop the latest master: https://github.com/Bodigrim/tar/tree/gnu-tar-long-filenames

**Comment by hasufell** [comment]
@Bodigrim cool... feel free to merge that as-is. I'll probably not be able to put in more work into tar at this point.

**Pull request merged**
