### PR TITLE
Allow newer tasty-quickcheck

### PR DESCRIPTION
**Pull request by andreasabel**
See:
- https://github.com/commercialhaskell/stackage/issues/7460

### CODE REVIEW

**Review by hasufell — APPROVED** [review]

**Comment by Bodigrim** [comment]
Thanks!

**Comment by andreasabel** [comment]
Can we get a revision for the sake of https://github.com/commercialhaskell/stackage/issues/7460 ?

**Comment by Bodigrim** [comment]
I usually don't do revisions for the sake of test suites, but feel free to make one if you feel it important enough.

**Comment by andreasabel** [comment]
2024-06-26T20:38:18Z  	AndreasAbel	  [tar-0.6.3.0-r1](https://hackage.haskell.org/package/tar-0.6.3.0/revisions)

**Pull request merged**
